name: Issue Template
description: Use this template to submit an issue.
title: "[Issue]: "
labels: bug
body:
  - type: input
    id: name
    attributes:
      label: Your Name
      description: Enter your full name.
      placeholder: John Doe
      required: true

  - type: input
    id: github_id
    attributes:
      label: Your GitHub User ID
      description: Enter your GitHub username.
      placeholder: johndoe123
      required: true

  - type: dropdown
    id: issue_folder
    attributes:
      label: Issue Folder
      description: Select the folder related to this issue.
      options:
        - med-o-ai
        - med-o-chat
        - med-o-next home
        - med-o-shop
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Describe the issue in detail.
      placeholder: Provide steps to reproduce, expected and actual behavior.
      required: true

  - type: checkbox
    id: agree_terms
    attributes:
      label: Agreement
      description: I agree to the terms and conditions of contributing to this project.
      required: true
